import React, { useState, useEffect } from 'react';
import type { Filament } from '../types';
import { ColorPickerCanvas } from './ColorPickerCanvas';

const normalizeHex = (colorStr: string): string => {
  if (!colorStr) return '#3b82f6';
  const trimmed = colorStr.trim();
  
  // Use HTML5 Canvas to normalize color values (names, rgb, hsl, hex) to hex
  try {
    const canvas = document.createElement('canvas');
    canvas.width = 1;
    canvas.height = 1;
    const ctx = canvas.getContext('2d');
    if (ctx) {
      ctx.fillStyle = trimmed;
      const parsedColor = ctx.fillStyle;
      if (parsedColor.startsWith('#')) {
        return parsedColor.toLowerCase();
      }
      const rgbMatch = parsedColor.match(/^rgba?\((\d+),\s*(\d+),\s*(\d+)/);
      if (rgbMatch) {
        const r = parseInt(rgbMatch[1], 10);
        const g = parseInt(rgbMatch[2], 10);
        const b = parseInt(rgbMatch[3], 10);
        return '#' + [r, g, b].map(x => {
          const hex = x.toString(16);
          return hex.length === 1 ? '0' + hex : hex;
        }).join('').toLowerCase();
      }
    }
  } catch (e) {
    console.error('Error normalizing hex', e);
  }

  if (trimmed.startsWith('#') && (trimmed.length === 7 || trimmed.length === 4)) {
    if (trimmed.length === 4) {
      const r = trimmed[1];
      const g = trimmed[2];
      const b = trimmed[3];
      return `#${r}${r}${g}${g}${b}${b}`.toLowerCase();
    }
    return trimmed.toLowerCase();
  }
  return '#3b82f6';
};

interface FilamentFormProps {
  filament?: Filament; // If editing
  existingFilaments: Filament[];
  geminiKey: string;
  onSave: (filament: Filament) => void;
  onDuplicateIncrement: (id: string) => void;
  onClose: () => void;
}

export const FilamentForm: React.FC<FilamentFormProps> = ({
  filament,
  existingFilaments,
  geminiKey,
  onSave,
  onDuplicateIncrement,
  onClose,
}) => {
  // Form states
  const [brand, setBrand] = useState(filament?.brand || '');
  const [type, setType] = useState(filament?.type || 'PLA');
  const [color, setColor] = useState(filament?.color || '');
  const [colorHex, setColorHex] = useState(normalizeHex(filament?.colorHex || '#3b82f6'));
  const [subTypes, setSubTypes] = useState<string[]>(filament?.subTypes || []);
  const [subTypeInput, setSubTypeInput] = useState('');
  const [nozzleTempMin, setNozzleTempMin] = useState<number | ''>(filament?.nozzleTempMin ?? '');
  const [nozzleTempMax, setNozzleTempMax] = useState<number | ''>(filament?.nozzleTempMax ?? '');
  const [bedTempMin, setBedTempMin] = useState<number | ''>(filament?.bedTempMin ?? '');
  const [bedTempMax, setBedTempMax] = useState<number | ''>(filament?.bedTempMax ?? '');
  const [printSpeed, setPrintSpeed] = useState<number | ''>(filament?.printSpeed ?? '');
  const [amount, setAmount] = useState<number>(filament?.amount ?? 1.0);
  const [description, setDescription] = useState(filament?.description || '');
  const [links, setLinks] = useState<Array<{ title: string; url: string }>>(
    filament?.links || []
  );
  const [pictures, setPictures] = useState<string[]>(filament?.pictures || []);

  // Auto-generation name flag - if editing or user manually changed the name, we don't overwrite it
  const [name, setName] = useState(filament?.name || '');
  const [isNameAutogenerated, setIsNameAutogenerated] = useState(!filament);

  // UI state
  const [isScanning, setIsScanning] = useState(false);
  const [isPickingColor, setIsPickingColor] = useState(false);
  const [duplicateFound, setDuplicateFound] = useState<Filament | null>(null);

  // Auto-generate name logic: "Brand Type Color SubType1 SubType2"
  useEffect(() => {
    if (isNameAutogenerated) {
      const subsStr = subTypes.join(' ');
      const autoName = `${brand} ${type} ${color} ${subsStr}`.trim().replace(/\s+/g, ' ');
      setName(autoName);
    }
  }, [brand, type, color, subTypes, isNameAutogenerated]);

  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setName(e.target.value);
    setIsNameAutogenerated(false);
  };

  const handleAddSubType = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' || e.key === ',') {
      e.preventDefault();
      const val = subTypeInput.trim();
      if (val && !subTypes.includes(val)) {
        setSubTypes([...subTypes, val]);
      }
      setSubTypeInput('');
    }
  };

  const removeSubType = (index: number) => {
    setSubTypes(subTypes.filter((_, idx) => idx !== index));
  };

  const handleAddLink = () => {
    setLinks([...links, { title: '', url: '' }]);
  };

  const handleLinkChange = (index: number, field: 'title' | 'url', value: string) => {
    const updated = [...links];
    updated[index][field] = value;
    setLinks(updated);
  };

  const removeLink = (index: number) => {
    setLinks(links.filter((_, idx) => idx !== index));
  };

  // Resize image client-side to save bandwidth and meet API limits
  const resizeImage = (base64Str: string, maxDimension = 1000): Promise<string> => {
    return new Promise((resolve) => {
      const img = new Image();
      img.src = base64Str;
      img.onload = () => {
        const canvas = document.createElement('canvas');
        let width = img.width;
        let height = img.height;

        if (width > height) {
          if (width > maxDimension) {
            height = Math.round((maxDimension / width) * height);
            width = maxDimension;
          }
        } else {
          if (height > maxDimension) {
            width = Math.round((maxDimension / height) * width);
            height = maxDimension;
          }
        }

        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext('2d');
        ctx?.drawImage(img, 0, 0, width, height);
        resolve(canvas.toDataURL('image/jpeg', 0.8));
      };
    });
  };

  const handlePictureUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files) return;

    Array.from(files).forEach((file) => {
      const reader = new FileReader();
      reader.onloadend = async () => {
        const rawBase64 = reader.result as string;
        const resized = await resizeImage(rawBase64);
        setPictures((prev) => [...prev, resized]);
      };
      reader.readAsDataURL(file);
    });
  };

  const deletePicture = (index: number) => {
    setPictures(pictures.filter((_, idx) => idx !== index));
  };

  // OCR Scan via Gemini
  const handleScanLabel = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!geminiKey) {
      alert('Please set your Gemini API Key in Settings first to scan packaging labels!');
      return;
    }

    setIsScanning(true);
    const reader = new FileReader();
    reader.onloadend = async () => {
      try {
        const originalBase64 = reader.result as string;
        const resizedBase64 = await resizeImage(originalBase64, 1024);

        // Extract raw base64 part
        const base64Data = resizedBase64.split(',')[1];

        const promptText = `Analyze this 3D printing filament label picture and extract details in raw JSON format.
Do NOT output markdown. Do NOT use markdown code blocks (\`\`\`json). Output raw JSON string exactly matching this schema:
{
  "brand": "String (e.g. eSUN, Overture, Hatchbox, Sunlu, Prusament, Elegoo - normalize casing/spacing)",
  "type": "String (e.g. PLA, PETG, ABS, ASA, TPU, Nylon - MUST be capitalized standard names)",
  "color": "String (e.g. Silk White, Galaxy Silver, Pine Green, Matte Black)",
  "colorHex": "String (Hex code like #ffffff, #000000, #3b82f6 representing the closest color of the filament)",
  "subTypes": ["Array of strings like Matte, High Flow, Silk, Glow in the dark, Carbon Fiber, Wood, Sparkly"],
  "nozzleTempMin": number or null,
  "nozzleTempMax": number or null,
  "bedTempMin": number or null,
  "bedTempMax": number or null,
  "printSpeed": number or null,
  "description": "Any comments or secondary specs seen on the label (spool weight, length, etc.)"
}
If a value is not found on the label, return null for that field. Make your best guess for the color and colorHex based on the photo content or label text.`;

        const response = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${geminiKey}`,
          {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              contents: [
                {
                  parts: [
                    { inlineData: { mimeType: 'image/jpeg', data: base64Data } },
                    { text: promptText },
                  ],
                },
              ],
              generationConfig: {
                responseMimeType: 'application/json',
              },
            }),
          }
        );

        if (!response.ok) {
          let errorMsg = response.statusText || `Status ${response.status}`;
          try {
            const errJson = await response.json();
            if (errJson?.error?.message) {
              errorMsg = errJson.error.message;
            }
          } catch (_) {}
          throw new Error(`Gemini API error: ${errorMsg}`);
        }

        const data = await response.json();
        const responseText = data.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!responseText) throw new Error('Empty response from Gemini API');

        const parsed = JSON.parse(responseText.trim());

        // Store picture in our preview list
        setPictures((prev) => [resizedBase64, ...prev]);

        // Check for duplicates in library
        const scannedBrand = parsed.brand || '';
        const scannedType = parsed.type || 'PLA';
        const scannedColor = parsed.color || '';

        const matched = existingFilaments.find(
          (f) =>
            f.brand.toLowerCase().trim() === scannedBrand.toLowerCase().trim() &&
            f.type.toUpperCase().trim() === scannedType.toUpperCase().trim() &&
            f.color.toLowerCase().trim() === scannedColor.toLowerCase().trim()
        );

        if (matched) {
          // Store duplicate reference to show modal prompt
          setDuplicateFound(matched);
          // Set temporary form states in case they want to create anyway
          fillFormFromScannedData(parsed);
        } else {
          // Pre-fill fields directly
          fillFormFromScannedData(parsed);
        }
      } catch (err) {
        console.error('OCR failed', err);
        alert(`Failed to extract data: ${err instanceof Error ? err.message : String(err)}`);
      } finally {
        setIsScanning(false);
      }
    };
    reader.readAsDataURL(file);
  };

  const fillFormFromScannedData = (parsed: any) => {
    if (parsed.brand) setBrand(parsed.brand);
    if (parsed.type) setType(parsed.type);
    if (parsed.color) setColor(parsed.color);
    if (parsed.colorHex) {
      setColorHex(normalizeHex(parsed.colorHex));
    } else if (parsed.color) {
      setColorHex(normalizeHex(parsed.color));
    }
    if (parsed.subTypes && Array.isArray(parsed.subTypes)) {
      // Merge unique
      setSubTypes(parsed.subTypes.filter(Boolean));
    }
    if (parsed.nozzleTempMin) setNozzleTempMin(parsed.nozzleTempMin);
    if (parsed.nozzleTempMax) setNozzleTempMax(parsed.nozzleTempMax);
    if (parsed.bedTempMin) setBedTempMin(parsed.bedTempMin);
    if (parsed.bedTempMax) setBedTempMax(parsed.bedTempMax);
    if (parsed.printSpeed) setPrintSpeed(parsed.printSpeed);
    if (parsed.description) setDescription(parsed.description);
  };

  const handleChooseDuplicateIncrement = () => {
    if (duplicateFound) {
      onDuplicateIncrement(duplicateFound.id);
      setDuplicateFound(null);
      onClose();
    }
  };

  const handleChooseDuplicateCreateNew = () => {
    // Dismiss duplicate prompt and keep form open with pre-filled details
    setDuplicateFound(null);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!brand.trim()) {
      alert('Brand is required!');
      return;
    }
    if (!type.trim()) {
      alert('Type is required!');
      return;
    }
    if (!color.trim()) {
      alert('Color name is required!');
      return;
    }

    const savedName = isNameAutogenerated
      ? name
      : name.trim() || `${brand} ${type} ${color} ${subTypes.join(' ')}`.trim().replace(/\s+/g, ' ');

    const newFilament: Filament = {
      id: filament?.id || crypto.randomUUID(),
      name: savedName,
      brand: brand.trim(),
      type: type.trim(),
      color: color.trim(),
      colorHex,
      subTypes,
      pictures,
      nozzleTempMin: nozzleTempMin === '' ? null : Number(nozzleTempMin),
      nozzleTempMax: nozzleTempMax === '' ? null : Number(nozzleTempMax),
      bedTempMin: bedTempMin === '' ? null : Number(bedTempMin),
      bedTempMax: bedTempMax === '' ? null : Number(bedTempMax),
      printSpeed: printSpeed === '' ? null : Number(printSpeed),
      amount: Number(amount),
      description: description.trim(),
      links: links.filter((l) => l.url.trim() !== ''),
      createdAt: filament?.createdAt || Date.now(),
      updatedAt: Date.now(),
    };

    onSave(newFilament);
  };

  return (
    <div className="overlay-backdrop" onClick={onClose}>
      <div className="bottom-sheet" onClick={(e) => e.stopPropagation()}>
        <div className="bottom-sheet-header">
          <h2>
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" style={{ color: 'var(--accent-color)' }}>
              <path d="M12 20h9M16.5 3.5a2.12 2.12 0 0 1 3 3L7 19l-4 1 1-4Z" />
            </svg>
            {filament ? 'Edit Filament Spool' : 'Add New Filament'}
          </h2>
          <button className="btn-icon" onClick={onClose} aria-label="Close form">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>

        <div className="bottom-sheet-content">
          {/* Smart Scan Banner */}
          {!filament && (
            <div style={{ marginBottom: '20px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <label className="btn-scan">
                {isScanning ? (
                  <>
                    <div className="spinner" style={{ width: '20px', height: '20px', borderWidth: '2px' }} />
                    <span>Analyzing Packaging...</span>
                  </>
                ) : (
                  <>
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                      <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
                      <circle cx="12" cy="13" r="4" />
                    </svg>
                    <span>Scan Label with Camera</span>
                  </>
                )}
                <input
                  type="file"
                  accept="image/*"
                  capture="environment"
                  onChange={handleScanLabel}
                  disabled={isScanning}
                  style={{ display: 'none' }}
                />
              </label>
            </div>
          )}

          {/* Main Form */}
          <form onSubmit={handleSubmit}>
            {/* Display Name Preview */}
            <div className="form-group">
              <label className="form-label">
                Filament Name <span style={{ fontSize: '0.75rem', fontWeight: 400, color: 'var(--text-muted)' }}>({isNameAutogenerated ? 'Autogenerated' : 'Custom'})</span>
              </label>
              <input
                type="text"
                className="form-input"
                value={name}
                onChange={handleNameChange}
                placeholder="e.g. eSUN PLA Peak Green Matte"
              />
              {!isNameAutogenerated && (
                <button
                  type="button"
                  onClick={() => setIsNameAutogenerated(true)}
                  style={{ background: 'none', border: 'none', color: 'var(--accent-color)', fontSize: '0.75rem', fontWeight: 600, alignSelf: 'flex-start', cursor: 'pointer', padding: '2px 0' }}
                >
                  Reset to autogenerated name
                </button>
              )}
            </div>

            <div className="form-group row-split">
              {/* Brand */}
              <div>
                <label className="form-label">
                  Brand <span className="required">*</span>
                </label>
                <input
                  type="text"
                  className="form-input"
                  value={brand}
                  onChange={(e) => setBrand(e.target.value)}
                  placeholder="e.g. eSUN, Sunlu"
                  list="brands-suggestions"
                  required
                />
                <datalist id="brands-suggestions">
                  {Array.from(new Set(existingFilaments.map((f) => f.brand))).map((b, idx) => (
                    <option key={idx} value={b} />
                  ))}
                </datalist>
              </div>

              {/* Type */}
              <div>
                <label className="form-label">
                  Material Type <span className="required">*</span>
                </label>
                <select
                  className="form-select"
                  value={type}
                  onChange={(e) => setType(e.target.value)}
                  required
                >
                  <option value="PLA">PLA</option>
                  <option value="PETG">PETG</option>
                  <option value="TPU">TPU</option>
                  <option value="ABS">ABS</option>
                  <option value="ASA">ASA</option>
                  <option value="Nylon">Nylon</option>
                  <option value="PET">PET</option>
                  <option value="PVA">PVA</option>
                  <option value="PC">PC</option>
                  <option value="HIPS">HIPS</option>
                  <option value="Wood">Wood</option>
                  <option value="Silk">Silk</option>
                  <option value="Custom">Custom</option>
                </select>
              </div>
            </div>

            <div className="form-group row-split">
              {/* Color Name */}
              <div style={{ flex: 2 }}>
                <label className="form-label">
                  Color Name <span className="required">*</span>
                </label>
                <input
                  type="text"
                  className="form-input"
                  value={color}
                  onChange={(e) => setColor(e.target.value)}
                  placeholder="e.g. Galaxy Black, Fire Red"
                  required
                />
              </div>

              {/* Color Hex Picker */}
              <div style={{ flex: 1, minWidth: '80px' }}>
                <label className="form-label">Picker</label>
                <div className="color-picker-input-group">
                  <input
                    type="color"
                    className="color-circle-input"
                    value={colorHex}
                    onChange={(e) => setColorHex(e.target.value)}
                  />
                  {pictures.length > 0 && (
                    <button
                      type="button"
                      className="btn-icon"
                      onClick={() => setIsPickingColor(true)}
                      title="Pick color from uploaded picture"
                      style={{ width: '44px', height: '44px' }}
                    >
                      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                        <path d="M2 22C4.5 19.5 8 18 10.5 15.5L18 8C20 6 20 3 18 1.5C16.5-0.5 13.5-0.5 11.5 1.5L4 9C1.5 11.5 0 15-2.5 17.5" />
                        <path d="m14 10 4 4" />
                      </svg>
                    </button>
                  )}
                </div>
              </div>
            </div>

            {/* Subtypes Tags */}
            <div className="form-group">
              <label className="form-label">Sub-Types (Press Enter / Comma to add)</label>
              <div className="tag-input-container">
                {subTypes.map((tag, idx) => (
                  <span key={idx} className="tag-pill">
                    {tag}
                    <button type="button" onClick={() => removeSubType(idx)}>&times;</button>
                  </span>
                ))}
                <input
                  type="text"
                  className="tag-input-field"
                  value={subTypeInput}
                  onChange={(e) => setSubTypeInput(e.target.value)}
                  onKeyDown={handleAddSubType}
                  placeholder="e.g. Matte, High Flow"
                />
              </div>
            </div>

            {/* Heat settings intervals */}
            <div className="form-group row-split">
              <div>
                <label className="form-label">Nozzle Temp Range (°C)</label>
                <div style={{ display: 'flex', gap: '6px', alignItems: 'center' }}>
                  <input
                    type="number"
                    className="form-input"
                    style={{ padding: '8px' }}
                    value={nozzleTempMin}
                    onChange={(e) => setNozzleTempMin(e.target.value === '' ? '' : Number(e.target.value))}
                    placeholder="Min"
                  />
                  <span>-</span>
                  <input
                    type="number"
                    className="form-input"
                    style={{ padding: '8px' }}
                    value={nozzleTempMax}
                    onChange={(e) => setNozzleTempMax(e.target.value === '' ? '' : Number(e.target.value))}
                    placeholder="Max"
                  />
                </div>
              </div>

              <div>
                <label className="form-label">Bed Temp Range (°C)</label>
                <div style={{ display: 'flex', gap: '6px', alignItems: 'center' }}>
                  <input
                    type="number"
                    className="form-input"
                    style={{ padding: '8px' }}
                    value={bedTempMin}
                    onChange={(e) => setBedTempMin(e.target.value === '' ? '' : Number(e.target.value))}
                    placeholder="Min"
                  />
                  <span>-</span>
                  <input
                    type="number"
                    className="form-input"
                    style={{ padding: '8px' }}
                    value={bedTempMax}
                    onChange={(e) => setBedTempMax(e.target.value === '' ? '' : Number(e.target.value))}
                    placeholder="Max"
                  />
                </div>
              </div>
            </div>

            <div className="form-group row-split">
              {/* Print speed */}
              <div>
                <label className="form-label">Print Speed (mm/s)</label>
                <input
                  type="number"
                  className="form-input"
                  value={printSpeed}
                  onChange={(e) => setPrintSpeed(e.target.value === '' ? '' : Number(e.target.value))}
                  placeholder="e.g. 150"
                />
              </div>

              {/* Amount (Spools count) */}
              <div>
                <label className="form-label">Amount (Spools) <span className="required">*</span></label>
                <input
                  type="number"
                  step="0.05"
                  min="0"
                  className="form-input"
                  value={amount}
                  onChange={(e) => setAmount(Number(e.target.value))}
                  required
                />
              </div>
            </div>

            {/* Description Notes */}
            <div className="form-group">
              <label className="form-label">Notes / Description</label>
              <textarea
                className="form-textarea"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="e.g. Print profile comments, specific shrinkage rates..."
              />
            </div>

            {/* Purchased sites/shops links */}
            <div className="form-group" style={{ marginBottom: '24px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '6px' }}>
                <label className="form-label">Purchase Links</label>
                <button
                  type="button"
                  onClick={handleAddLink}
                  style={{ background: 'none', border: 'none', color: 'var(--accent-color)', fontSize: '0.8rem', fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '3px' }}
                >
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                    <line x1="12" y1="5" x2="12" y2="19" />
                    <line x1="5" y1="12" x2="19" y2="12" />
                  </svg>
                  Add Link
                </button>
              </div>

              <div className="links-editor-list">
                {links.map((link, idx) => (
                  <div key={idx} className="link-item-row">
                    <input
                      type="text"
                      className="form-input"
                      style={{ flex: 1, padding: '8px' }}
                      value={link.title}
                      onChange={(e) => handleLinkChange(idx, 'title', e.target.value)}
                      placeholder="Title (e.g. Amazon)"
                    />
                    <input
                      type="url"
                      className="form-input"
                      style={{ flex: 2, padding: '8px' }}
                      value={link.url}
                      onChange={(e) => handleLinkChange(idx, 'url', e.target.value)}
                      placeholder="URL (https://...)"
                      required
                    />
                    <button
                      type="button"
                      className="btn-icon"
                      onClick={() => removeLink(idx)}
                      style={{ width: '38px', height: '38px', borderColor: 'rgba(239, 68, 68, 0.3)' }}
                    >
                      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" style={{ color: 'var(--danger-color)' }}>
                        <line x1="18" y1="6" x2="6" y2="18" />
                        <line x1="6" y1="6" x2="18" y2="18" />
                      </svg>
                    </button>
                  </div>
                ))}
              </div>
            </div>

            {/* Spool Photos Upload/Preview manager */}
            <div className="form-group" style={{ marginBottom: '24px' }}>
              <label className="form-label">Filament Photos ({pictures.length})</label>
              <div className="pictures-grid">
                {pictures.map((pic, idx) => (
                  <div key={idx} className="picture-slot">
                    <img src={pic} alt={`uploaded preview ${idx}`} />
                    <div className="slot-controls">
                      <button
                        type="button"
                        className="slot-btn"
                        onClick={() => deletePicture(idx)}
                        style={{ background: 'rgba(239, 68, 68, 0.8)' }}
                        title="Delete photo"
                      >
                        ×
                      </button>
                    </div>
                  </div>
                ))}
                {/* Option 1: Take Photo via Camera */}
                <label className="picture-upload-placeholder" title="Take photo using camera">
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
                    <circle cx="12" cy="13" r="4" />
                  </svg>
                  <span>Camera</span>
                  <input
                    type="file"
                    accept="image/*"
                    capture="environment"
                    onChange={handlePictureUpload}
                    style={{ display: 'none' }}
                  />
                </label>

                {/* Option 2: Upload from Gallery */}
                <label className="picture-upload-placeholder" title="Choose photo from gallery">
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                    <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
                    <circle cx="8.5" cy="8.5" r="1.5" />
                    <polyline points="21 15 16 10 5 21" />
                  </svg>
                  <span>Gallery</span>
                  <input
                    type="file"
                    accept="image/*"
                    onChange={handlePictureUpload}
                    multiple
                    style={{ display: 'none' }}
                  />
                </label>
              </div>
            </div>

            {/* Actions */}
            <div className="form-actions">
              <button type="button" className="btn-secondary" onClick={onClose}>
                Cancel
              </button>
              <button type="submit" className="btn-primary">
                Save Filament
              </button>
            </div>
          </form>
        </div>
      </div>

      {/* Duplicate Prompt Dialog */}
      {duplicateFound && (
        <div className="overlay-backdrop" style={{ zIndex: 2000, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '20px' }}>
          <div className="bottom-sheet" style={{ maxWidth: '400px', borderRadius: 'var(--radius-lg)' }} onClick={(e) => e.stopPropagation()}>
            <div className="bottom-sheet-header">
              <h2 style={{ color: 'var(--warning-color)' }}>
                <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" style={{ marginRight: '6px' }}>
                  <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z" />
                  <line x1="12" y1="9" x2="12" y2="13" />
                  <line x1="12" y1="17" x2="12.01" y2="17" />
                </svg>
                Duplicate Detected!
              </h2>
            </div>
            <div className="bottom-sheet-content">
              <p style={{ fontSize: '0.95rem', lineHeight: '1.5', color: 'var(--text-primary)' }}>
                A filament for <strong>{duplicateFound.brand} {duplicateFound.type}</strong> in the color <strong>{duplicateFound.color}</strong> already exists in your library.
              </p>
              <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginTop: '8px' }}>
                Would you like to increment the spool count of your existing spool, or create an entirely new filament record?
              </p>

              <div className="duplicate-modal-buttons">
                <button
                  type="button"
                  className="btn-primary"
                  onClick={handleChooseDuplicateIncrement}
                >
                  Increment Spool Count (+1 Spool)
                </button>
                <button
                  type="button"
                  className="btn-secondary"
                  onClick={handleChooseDuplicateCreateNew}
                >
                  Create New Duplicate Entry
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Canvas Color Picker Modal */}
      {isPickingColor && pictures.length > 0 && (
        <ColorPickerCanvas
          pictureSrc={pictures[0]}
          initialColor={colorHex}
          onColorPicked={(pickedHex) => {
            setColorHex(pickedHex);
            setIsPickingColor(false);
          }}
          onClose={() => setIsPickingColor(false)}
        />
      )}
    </div>
  );
};
